// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYT4WP-6Yt9VdnWYo5DfWLKqwf36haf9g',
    appId: '1:440928927861:web:4874e203c74557359c383c',
    messagingSenderId: '440928927861',
    projectId: 'note-with-me-flutter',
    authDomain: 'note-with-me-flutter.firebaseapp.com',
    storageBucket: 'note-with-me-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCriNdR4snzItB_McruAhULcQ5X9BzbsnQ',
    appId: '1:440928927861:android:a0dac4dcdcb668549c383c',
    messagingSenderId: '440928927861',
    projectId: 'note-with-me-flutter',
    storageBucket: 'note-with-me-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDroPZQGlOOskf2pkT_ZZBtoOTRY9sW5pE',
    appId: '1:440928927861:ios:1852db7faba0eee69c383c',
    messagingSenderId: '440928927861',
    projectId: 'note-with-me-flutter',
    storageBucket: 'note-with-me-flutter.appspot.com',
    iosClientId: '440928927861-ap56qoa0jdqtc8s6nvccjbje5jpifh1k.apps.googleusercontent.com',
    iosBundleId: 'net.yunusemrehancer.notewithme',
  );
}
